# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 400)
        MainWindow.setMinimumSize(QtCore.QSize(300, 400))
        MainWindow.setMaximumSize(QtCore.QSize(300, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 300, 400))
        self.frame.setStyleSheet("background-color: rgb(40, 40, 40);\n"
"font: 16pt \"Book Antiqua\";\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_run = QtWidgets.QPushButton(self.frame)
        self.btn_run.setGeometry(QtCore.QRect(20, 350, 260, 31))
        self.btn_run.setStyleSheet("background-color: rgb(9, 93, 0);\n"
"padding-left: 10px;\n"
"border-radius: 10px;")
        self.btn_run.setObjectName("btn_run")
        self.input_path = QtWidgets.QLineEdit(self.frame)
        self.input_path.setGeometry(QtCore.QRect(20, 120, 260, 30))
        self.input_path.setStyleSheet("font: 75 10pt \"Book Antiqua\";\n"
"padding-left: 10px;\n"
"border-radius: 10px;\n"
"background-color: rgb(53, 53, 53);\n"
"")
        self.input_path.setObjectName("input_path")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 26, 261, 71))
        self.label.setStyleSheet("word-wrap: wrap;\n"
"font: 75 12pt \"Book Antiqua\";")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.frame)
        self.textEdit.setGeometry(QtCore.QRect(20, 170, 260, 160))
        self.textEdit.setMinimumSize(QtCore.QSize(260, 160))
        self.textEdit.setMaximumSize(QtCore.QSize(260, 160))
        self.textEdit.setStyleSheet("padding: 5px;\n"
"font: 10pt \"Arial\";\n"
"word-wrap: wrap;")
        self.textEdit.setTabChangesFocus(False)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_run.setText(_translate("MainWindow", "Выполнить"))
        self.input_path.setPlaceholderText(_translate("MainWindow", "Введите путь к папке"))
        self.label.setText(_translate("MainWindow", "Cleaner отсортирует файлы по папкам: Video, Audio, Pictures, Documents, other"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Book Antiqua\'; font-size:12pt; font-style:italic;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
